### ISSUE TITLE
How to use this code on the BCH code?

### ISSUE THREAD

**Issue by raeyyyyy** [yoniLc/ECCT#1]
Hi,
How do I use this code to train a network model to realize BCH encode and decode? How should I modify the code?
Thanks

**Comment by yoniLc** [comment]
Hi, 
after you provide the parity check matrix in the Codes_DB folder (or use one of the codes already there), just train with the right flags, e.g., using one of the codes currently there run with the following flags `--code_type=BCH--code_n=63 --code_k=36`.
